apiVersion: v2
name: fm-services
description: A Helm chart for fm services

type: application

version: "0.1.0-0"          # The version of the chart
appVersion: "0.1.2"       # The version of the application enclosed by the chart

home: "https://github.com/Flairminds/ath-argo-test/charts/fm-services"

sources:
  - "https://github.com/Flairminds/ath-argo-test/charts/fm-services"

keywords:
  - fm
  - services

maintainers:
  - name: DevOps Team
    email: devops@fm.com

annotations:
  category: Application
  access: Private
  fm.com/license: "Proprietary"
  fm.com/support: "support@fm.com"
  fm.com/owner: "fm"
  fm.com/team: "DevOps"

dependencies:
  # TODO: Copy dep chart locally or use something better. [ TBD ]
  - name: "common-res"
    version: "1.0.19"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: "common-res.enabled"

  - name: prometheus-service-discovery
    version: "40.1.0-5"
    repository: "oci://ghcr.io/luminartech/helm-charts-public"
    condition: prometheus-service-discovery.enabled
