apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-common-gitops-infra
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: development
  source:
    directory:
      recurse: true
    path: deploy/common
    repoURL: git@github.com:nexla/gitops-infra-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - Prune=false
