---
# This project is for all shared applications launched as per the applicationsets configurations
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cicd
spec:
  description: Argo CD project for CICD applications
  sourceRepos:
  - '*'
  destinations:
  - name: "*"
    server: "*"
    namespace: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
